#!/usr/bin/env python3 

# import modules
import sys, re, getopt, os.path, mimetypes
from urllib.parse import unquote

#=================================================#
# sys       = system access to open files
# re        = regular expressions
# getopt    = check script arguments and options
# os.path   = check if first argument is a file
# mimetypes = check if file is a text file
# unquote   = decode urls
#=================================================#

#=================================================#
# script usage function
#=================================================#

def usage():
    '''script usage
    
    display script usage when the -h or --help option is used
    '''
    usage = """
-h --help display help
-i 'video url'
-t '00:00:00'

rip-record -i <video-url> -t <00:00:00>
    """
    print(usage)


#=================================================#
# checkurl function - check if first arg is text file
#=================================================#

# pass argv[1] which is the first argument with the url -
# to the checkurl function
# use os.path.isfile to check if the the first arg -
# is a file, then use mimetypes to check if its a text file
# if it is a text file, read the contents -
# and set the variable url to equal the contents of the text file
# if its not a text file - url variable is 
# the function just prints the url at the moment
# should return the url


def checkurl(url):
    ''' check first argument passed to script
    
    check if first argument passed to script, 
    is a text file and if so open it and read the contents,
    and set the variable url to equal the contents of the text file.
    if the first argument isnt a text file its on the command line
    
    then check if the string is a url
    '''
    if os.path.isfile(url):
        if mimetypes.guess_type(url)[0] == 'text/plain':
            file = open(url, 'r') 
            url = file.read() 
            file.close()          
            return url
    x = re.compile(r'^(http|https|rtmp|rtmpe)://[a-zA-Z0-9./]+[./]+[a-zA-Z]+[a-zA-Z0-9]+.*$')
    if not x.match(url):
        usage()    # display script usage
        sys.exit() # exit
    return url

#=================================================#
# validation functions
#=================================================#

# functions to validate the url which comes after -i
# and the duration which comes after -t

# the url should start with http|https|rtmp|rtmpe://
# the duration should match 00:00:00 format
# 0-9 followed by : 0-9 followed by : 0-9 followed by :

# these are the bash regular expressions which should work with python
# the function should validate the url and duration with regulat expressions
# and if the user input doesnt match the regexs display script usage and exit

def duration_validated(duration):
    ''' validate user input for second argument

    user regular expressions to check duration matches 00:00:00 format
    '''
    y = re.compile('^[0-9]{2}:[0-9]{2}:[0-9]{2}$')
    if not y.match(duration):
        usage()    # display script usage
        sys.exit() # exit
    return duration


#=================================================#
# main function
#=================================================#

def main(argv):
    ''' main function
    
    check number of arguments passed to script
    '''
#=================================================#
# check number of arguments passed to script
#=================================================#

# check number of arguments passed to script
# if script is run with no arguments display script usage and exit
# if script is run with more than 4 arguments passed to the script
# display script usage and exit

    if len(argv) == 0:  # no arguments passed to script
        print("No arguments passed to script")
        usage()    # display script usage
        sys.exit() # exit
    elif len(argv) > 4: # too many arguments passed to script
        print("Too many arguments passed to script")
        usage()    # display script usage
        sys.exit() # exit

#=================================================#
# try options
#=================================================#

# options
# h = help
# i: = url, the : means i requires an argument which would be the url
# t: = time, the : means t requires an argument which would be the time in 00:00:00 format

    try:
        opts, args = getopt.getopt(argv, "hi:t:", ["help", "url", "time"])
    except getopt.GetoptError as err: 
        print(err)  # will print something like "option -x not recognized"
        usage()     # display script usage
        sys.exit(2) # exit
      
#=================================================#
# check options and arguments
#=================================================#

    for opt, arg in opts:
        if opt in ("-h", "--help"):
            # -h or --help = display help
            usage()
            sys.exit()
        elif opt == ("-i") and len(argv) == 2:
            # -i and url or text file - argv length 2, valid options and args
            checkurl(argv[1]) # checkurl function
        elif opt == ("-t") and len(argv) == 2:
            # -t option on its own - invalid
            print("the -t option must be used after the -i option")
            usage()
            sys.exit()
        elif opt in ("-i", "-t") and len(argv) == 4:
            if "-t" in opts[0]:
                # -t option used before -i option - invalid
                print("the -t option must be used after the -i option")
                usage()
                sys.exit()
            else:
                # -i url followed by -t 00:00:00 = valid
                checkurl(argv[1]) # checkurl function
                duration_validated(argv[3])
        else:
            assert False, "unhandled option"



#=================================================#
# decode url and split
#=================================================#

        if len(argv) == 2:
            url_decoded = unquote(unquote(checkurl(argv[1])))
            print("2 args")
        elif len(argv) == 4:
            url_decoded = unquote(unquote(checkurl(argv[1])))
            time = duration_validated(argv[3])
            print("4 args")


        slash = re.compile(r'^(http|https)://[a-zA-Z0-9:0-9./?=_,@&%-]+\.(m3u8|mkv|mp4|avi|flv)[|]+.*$')
        qmark = re.compile(r'^(http|https)://[a-zA-Z0-9:0-9./?=_,@&%-]+\.(m3u8|mkv|mp4|avi|flv)[?]+([a-zA-Z0-9?&=%*_-]*[^|])+.*$')

        if slash.match(url_decoded):
            print("match |")
        elif qmark.match(url_decoded):
            print("match ?")
        else:
            print("no match")
            
#        url_split = url_decoded.split('|')

#url_list = [v.split('=', 1) for v in decoded_url if '=' in v]
#print(url_list)


#=================================================#
# slice off script name from arguments
#=================================================#

if __name__ == "__main__":
    main(sys.argv[1:])

   
