#!/usr/bin/env python3 

# import modules
import validate
import regex
import sys, re, getopt, os.path, mimetypes
from urllib.parse import unquote

#=================================================#
# sys       = system access to open files
# re        = regular expressions
# getopt    = check script arguments and options
# os.path   = check if first argument is a file
# mimetypes = check if file is a text file
# unquote   = decode urls
#=================================================#

# argv
argv = sys.argv[1:]

# shortcuts for imported functions

usage = validate.usage
checkurl = validate.checkurl
durationValidated = validate.durationValidated
argLength = validate.argLength
splitUrl = regex.splitUrl
splitEquals = regex.splitEquals

#=================================================#
# main function
#=================================================#

def main(argv):
    ''' main function
    
    check number of arguments passed to script
    '''
    
#=================================================#
# check number of arguments passed to script
#=================================================#

# if script is run with no arguments or more than 4 arguments
# display script usage and exit

    argLength(argv)

#=================================================#
# check options and arguments
#=================================================#

# h = help
# i: = url, the : means i requires an argument which would be the url
# t: = time, the : means t requires an argument which would be the time in 00:00:00 format

    try:
        opts, args = getopt.getopt(argv, "hi:t:", ["help", "url", "time"])
    except getopt.GetoptError as err: 
        print(err)  # will print something like "option -x not recognized"
        usage()     # display script usage
        sys.exit(2) # exit

    for opt, arg in opts:
        if opt in ("-h", "--help"):
            # -h or --help = display help
            usage()
            sys.exit()
        elif opt == ("-i") and len(argv) == 2:
            # -i and url or text file - argv length 2, valid options and args
            checkurl(argv[1]) # checkurl function
        elif opt == ("-t") and len(argv) == 2:
            # -t option on its own - invalid
            print("the -t option must be used after the -i option")
            usage()
            sys.exit()
        elif opt in ("-i", "-t") and len(argv) == 4:
            if "-t" in opts[0]:
                # -t option used before -i option - invalid
                print("the -t option must be used after the -i option")
                usage()
                sys.exit()
            else:
                # -i url followed by -t 00:00:00 = valid
                checkurl(argv[1]) # checkurl function
                durationValidated(argv[3])
        else:
            assert False, "unhandled option"


#=================================================#
# decode url and split
#=================================================#

# pass the decoded url to the url_split function

        #x = splitUrl(urlDecoded)
        #print(x)
           
#        url_split = x.split(r'&')
#        url_list = [v.split('=', 1) for v in url_split if '=' in v]
#        y = dict(url_list)


#=================================================#
# slice off script name from arguments
#=================================================#

if __name__ == "__main__":
    main(sys.argv[1:])

    if len(argv) == 2:
        urlDecoded = unquote(unquote(checkurl(argv[1])))
    elif len(argv) == 4:
        urlDecoded = unquote(unquote(checkurl(argv[1])))
        time = duration_validated(argv[3])
    
    x = splitUrl(urlDecoded)
    print(x)
