#!/usr/bin/env python3

import sys, os
from datetime import datetime

#home = os.path.expanduser('~').replace('\\', '/')
home = os.path.expanduser('~')
now = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
arg = str(sys.argv[1])
thepath = home + "/Desktop/video-url-" +str(now) +".txt"
f = open(thepath, "w")
content = arg
f.write(content)
f.close()
